# Meta
backend = "glx";
vsync = false;
shadow = false;

# Fading
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-delta = 8;

# Opacity
inactive-opacity = 1.0;
active-opacity = 1.0;
frame-opacity = 1.0;
detect-client-opacity = true;

# Blur
blur-method = "dual_kawase";
blur-strength = 4;
blur-background = true;
blur-background-frame = true;
unredir-if-possible = true;


rules = (
    # Defaults
    {
        blur-background = false;
    },

    # Enable blur only for Alacritty.
    {
        match = "class_g = 'Alacritty'";
        blur-background = true;
        unredir = false;
    },

    # Firefox may unredirect when fullscreen.
    {
        match = "class_g = 'firefox'";
        opacity = 1.0;
        unredir = true;
    },


    # Termichan dropdown terminal animations.
    {
        match = "class_i = 'termichan'";

        animations = (
            {
                triggers = [ "open", "show" ];
                preset = "fly-in";
                direction = "down";
                duration = 0.20;
            },
            {
                triggers = [ "close", "hide" ];
                preset = "slide-out";
                direction = "down";
                duration = 0.20;
            }
        );
    }
);
