#GLOBALS
command=/home/owo/.config/i3/scripts/$BLOCK_NAME
separator_block_width=30
separator=false
markup=none
color=#FFFFFF

border=#8D8FF4
border_left=0
border_right=0
border_top=0
border_bottom=0

#Auryo Soundcloud current playing track
[soundcloud]
border=#FF8C00
color=#FFFFFF
#color=#20252C
border_bottom=1
label= 
interval=1
separator_block_width=50

[playerctl]
color=#FFFFFF
border=#FF8C00
border_bottom=1
label=♫ 
interval=1
separator_block_width=50

# Displays how many days left to target day
# eg: New season release of Non Non Biyori
#[pause]
#full_text= 
#command=playerctl play-pause;echo " "

# Displays how many days left to target day
# eg: New season release of Non Non Biyori
#[left_days]
#label=
#interval=3600

# Wifi SSID if connected
[wifiSSID]
command=iwgetid -r | cut -c -12
#color=#20242D
label=
interval=120

# Green Tunnel Switch
[greentunnel]
full_text=

# Hourly weather
[weather]
label=
interval=300

# Date Time
[time]
label=
command=date '+ %d %B %H:%M '
interval=60
align=right
min_width= 00 October 00:00
