#!/usr/bin/env python3

"""
[crypto]
label=
markup=pango
interval=60
instance=BTC
"""

from os import environ
from json import loads
from requests import get
from re import compile as regex
from re import sub

coin = environ.get('BLOCK_INSTANCE')
r = loads(
    get("https://api.binance.com/api/v3/ticker/24hr",params={'symbol':coin}).text
)

coin = sub('BTC$|USDT$|BNB$|TRY$','',coin)

prcnt = round(float(r['priceChangePercent']),1)
price = regex(r'(?:(\.)|(\.\d*?[1-9]\d*?))0+(?=\b|[^0-9])').sub(r'\2',r['lastPrice'])

if float(prcnt) > 0:
    percentChange=f'<span color="#3BB92D">{prcnt}%</span>'
else:
    percentChange=f'<span color="#F7555E">{prcnt}%</span>'


print(f"{coin} {price} {percentChange}")
