#!/usr/bin/env python3

"""
[kripto]
label=
markup=pango
interval=60
instance=BTC
"""

from os import environ
from json import loads
from requests import get

coin = environ.get('BLOCK_INSTANCE')

r = loads(
    get("https://api.btcturk.com/api/v2/ticker",params={"pairSymbol":f"{coin}_TRY"}).text
)['data'][0]


if r['dailyPercent'] > 0:
    percentChange=f'<span color="#3BB92D">{r["dailyPercent"]}%</span>'
else:
    percentChange=f'<span color="#F7555E">{r["dailyPercent"]}%</span>'


print(f"{coin} {int(r['last'])} {percentChange}")
