#!/usr/bin/python3
# I added a feature that logs current playing track/artist to Auryo Soundcloud Player
# which made us able to pull them and print it to our status bar
# Here is my fork: https://github.com/Kebablord/Auryo (it's included in auryo's official latest release)

from os import system

log = open("/tmp/auryo_status.log",mode="r").readlines()
title = log[0].rstrip()
artist = log[1].rstrip()

if (' (' in title):
  title = title[:title.index(' (')]

if (' [' in title):
  title = title[:title.index(' [')]

if ('-' in title):
  artist = ''
  if not(' -' in title):
      title.replace('-',' -')
else:
  artist += ' - '

if not(system('pidof auryo >/dev/null')):
  print(artist+title)
else:
  print('')
